### PR TITLE
[WIP] Set spark.testing in SharedOapContextBase

### LINKED ISSUE #877: TestSuite extends SharedOapContext can't run Independent
Independent run a test suite exetnds SharedOapContext(like `FilterSuite`)  in ide will errors as following stack, but maven test no problems.
```
Exception encountered when invoking run on a nested suite - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at org.apache.spark.sql.hive.thriftserver.OapEnv$.initWithoutCreatingOapSession(OapEnv.scala:82)
	at org.apache.spark.sql.oap.OapDriverRuntime.<init>(OapRuntime.scala:57)
	at org.apache.spark.sql.oap.OapRuntime$.init(OapRuntime.scala:155)
	at org.apache.spark.sql.oap.OapRuntime$.init(OapRuntime.scala:145)
	at org.apache.spark.sql.oap.OapRuntime$.getOrCreate(OapRuntime.scala:138)
	at org.apache.spark.sql.test.oap.SharedOapContext$class.createSparkSession(SharedOapContext.scala:35)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.createSparkSession(FilterSuite.scala:34)
	at org.apache.spark.sql.test.SharedSQLContext$class.beforeAll(SharedSQLContext.scala:62)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.org$apache$spark$sql$test$oap$SharedOapContextBase$$super$beforeAll(FilterSuite.scala:34)
	at org.apache.spark.sql.test.oap.SharedOapContextBase$class.beforeAll(SharedOapContext.scala:60)
	at org.apache.spark.sql.execution.datasources.oap.FilterSuite.beforeAll(FilterSuite.scala:42)
	at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
	at org.apache.spark.SparkFunSuite.beforeAll(SparkFunSuite.scala:31)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
	at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:31)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

### PR DESCRIPTION
**Pull request by gczsjdy**
## What changes were proposed in this pull request?

To resolve #877 

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by LuciferYang** [comment]
Will cause `mvn test` failed :( ... and the suites extends SharedOapLocalClusterContext will can not run in ide, lack 'spark.test.home'

**Comment by gczsjdy** [comment]
Originally in IDE we are also not able to run in LocalCluster mode

**Comment by gczsjdy** [comment]
I have tried manually set spark.test.home, SPARK_SCALA_VERSION, as what maven did, but still there are problems. I think probably it's best these work is not done in OAP, but we only did it in OAP local mode for convenience

**Comment by LuciferYang** [comment]
From travis log I found that if we add ` System.setProperty("spark.testing", "true")` line ,`mvn test` will failed.... @gczsjdy

**Comment by gczsjdy** [comment]
@LuciferYang Yep, but pretty occupied these days, maybe reconsider for a better solution later : )

**Pull request closed without merging**
