### PR TITLE
[OAP-1918][OAP-CACHE][POAE7-563]bug fix: plasma get an invalid value

### PR DESCRIPTION
**Pull request by offthewall123**
## What changes were proposed in this pull request?

bug fix: plasma get an invalid value

## How was this patch tested?

E2E

### CODE REVIEW

**Comment by offthewall123** [comment]
@jikunshang @yeyuqiang @winningsix  Please take a review, thanks.

**Comment by jikunshang** [comment]
LGTM.

**Comment by winningsix** [comment]
@offthewall123 is it OK to commit? The title is still in WIP while dashboard shows completed.

**Comment by winningsix** [comment]
close #1918

**Comment by winningsix** [comment]
close #1918

**Pull request merged**
