### PR TITLE
Add the bitmap index common interfaces v0.2

### PR DESCRIPTION
**Pull request by lee-lei**
This is the first version. The next version will
add the arguments and return types.

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by lee-lei** [comment]
This is the initial version. The arguments and return types will be added soon. And these interfaces still need to polish. Welcome comments and suggestions!

**Comment by lee-lei** [comment]
Just forgot to add the missing commit. Thanks.

**Comment by yueawang** [comment]
My understanding is this is index file read/write interface, and scan/query logic is not included. Maybe another class who is composed by this one is able to implement the query logic, correct??

**Comment by lee-lei** [comment]
He is now adding the arguments and return values of these common interfaces. And meanwhile he is working out to integrate them into the existing OAP implementations. Thanks.

**Comment by yueawang** [comment]
Can you host a review meeting for you ideas & implementations, maybe after you finish adding argument. Thanks!

**Comment by lee-lei** [comment]
My rough plan is below:
1. get the minimual code changes based on the existing bitmap index implementation to achieve the goal of parital loading for bitmap index.
    1.1 save the sorted key set to statics manager which is already using it to avoid the repetitive sort during index scanning.
    1.2 save the sorted bitmap to bitmap index file.
    1.3 since the exisitng bitmap index implementation is using fixed size BitSet. It's easy to locate the bitmaps with expected ranges from the above sorted key set.
2. port the widely using third-party bitmap index implementation (e.g. roaring bitmap) to OAP.

**Comment by lee-lei** [comment]
3. Meanwhile, get the interfaces more general for both the existing bitmap implementation and third party. Welcome your comments for my plan. Thanks.

**Comment by lee-lei** [comment]
Strictly speaking, the sorted key set are also saved to index file. After that, it's sorted the bitmaps. In other words, the sorted keys and corresponding bitmaps are saved separately which have below benefits:
1. avoid the repetitive key sorting for each bitmap index scanning.
2. achieve the partial load for both key set and expected bitmaps.

**Comment by lee-lei** [comment]
After finishing the above, he will work out one micro benchmark to evaluate the performance and opportunities ahead. Thanks.

**Comment by linhong-intel** [comment]
I think this PR is not needed any more. Can we close it?

**Comment by lee-lei** [comment]
Thanks for closing this PR. We can pick up some idea within these interfaces if it's useful in the future. Thanks.

**Pull request closed without merging**
