### PR TITLE
Use OapSession in Test Suite

### PR DESCRIPTION
**Pull request by linhong-intel**
## What changes were proposed in this pull request?

This is similar to SharedSQLContext
How to use:
`class OapIndexQuerySuite extends QueryTest with SharedSQLContext`
change to
`class OapIndexQuerySuite extends QueryTest with OapSharedSQLContext`

Current problem (Solved):
~~~To use OapSession, hive support must be enable. Then table info is stored in disk. `sql("Create Table tablename")` can fail if the table exists~~~


## How was this patch tested?
mvn test

### CODE REVIEW

**Comment by linhong-intel** [comment]
This PR is OK to review now.

**Comment by linhong-intel** [comment]
I uploaded another version of TestContext in file "TestOap". Please check if it's the one you want.

**Comment by adrian-wang** [comment]
There are two object TestOAPContext in your code ...

**Comment by linhong-intel** [comment]
close it until I find out a better solution

**Pull request closed without merging**
