### PR TITLE
Import Vectorized Reader code from spark

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?
SubTask 1 of #825(#829),  import `VectorizedRleValuesReader`, `VectorizedPlainValuesReader` ,`VectorizedRleValuesReader` from Spark Code include 2.1 & 2.2, will change some access modifer of these class.

## How was this patch tested?

mvn test pass

### CODE REVIEW

**Comment by gczsjdy** [comment]
Thanks @LuciferYang , also upload Spark 2.2 code here and merge in 1 shot?

**Comment by gczsjdy** [comment]
Seems some files don't change across versions like `VectorizedPlainValuesReader.java`? Could you check that? If yes we can only upload one file to src/main/java/....

**Comment by LuciferYang** [comment]
@gczsjdy But it will change in version 2.3, I think we should keep a copy for each major version.

**Comment by gczsjdy** [comment]
@LuciferYang Makes sense, LGTM.

**Comment by gczsjdy** [comment]
Merging this, don't forget to update 'Spark API change: 2.1 & 2.2'

**Pull request merged**
