### PR TITLE
Fix the parquet cache ineffective issue

### PR DESCRIPTION
**Pull request by zhangweilst**
## What changes were proposed in this pull request?

1. Add the procedure to determine whether the ParquetFileFormat should be converted to OapFileFormat.
2. Change the condition statement accordingly.

## How was this patch tested?

Tested the code manually with DailyTest.

### CODE REVIEW

**Comment by LuciferYang** [comment]
If `OAP_PARQUET_DATA_CACHE_ENABLED` is true, always use OapFileFormat? I don't think it's time to do this, first of all, the performance of cache has not reached our expectations, especially the first data loading, it will slow 120% than without index. On the other hand, if memory  is not large enough will trigger frequent dataCache exchange, production environment does not  accept this problem. @zhangweilst Now, I prefer to add a `test option` to test parquet full table scan with datacache.

**Comment by LuciferYang** [comment]
@zhangweilst On the other hand, if use OapFileFormat read parquet file when enable parquet datacache for full table scan , please ensure OapFileForamat.getHitIndexColumns method logic correctness.

**Comment by zhangweilst** [comment]
@LuciferYang OK, I see your point. I'll add an option to handle full table scan situation. Thanks!

**Comment by linhong-intel** [comment]
we don't need this for now. close it.

**Pull request closed without merging**
