### PR TITLE
[remote-shuffle] Shuffle reader batch fetch

### PR DESCRIPTION
**Pull request by gczsjdy**
## What changes were proposed in this pull request?

When Adaptive Execution is enabled, reduce partitions may be coalesced to a larger ShuffleBatchBlock, and there's chance to read consecutive bytes in one shot.

## How was this patch tested?

UTs, more to be added.
Distributed testing(with `spark.read.text("hdfs://gsr139:8020/HiBench/Repartition/Input3").groupBy("value").count.foreach(_=> {})`) at 200GB passed, AE will coalesce the partition to fewer.

### CODE REVIEW

**Comment by zhouyuan** [comment]
the failure on native sql is due to some wrong dependencies of spark, the tests are temporarily disabled.

**Comment by gczsjdy** [comment]
Thank you @zhouyuan , let me retrigger the CI build.

**Comment by carsonwang** [comment]
@gczsjdy , can you please pass the tests?

**Comment by zhouyuan** [comment]
@gczsjdy can you please do a rebase? it should be fixed on master

**Comment by gczsjdy** [comment]
yep @zhouyuan @carsonwang  ^^

**Pull request merged**
