### PR TITLE
[DONT MERGE] Comparison between isFiltered is used by DataSourceScanExec or not #598

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?
As #598 discussed, try to Comparison between ColumnBatch.isFiltered method is used by DataSourceScanExec or not.
This pr is related code modification, and then I will give some performance comparison data.
Don't merge this before we get a conclusion.

### CODE REVIEW

**Comment by LuciferYang** [comment]
@linhong-intel Next Step I will do performance test between this pr and current master version, there is a related influence of oapMetrics because in this pr read granularity is batch, the actually read count is more then oapMetrics contents.

**Comment by LuciferYang** [comment]
@linhong-intel I try to do this comparison between oap-0.3, current master and this pr, there are 4 use index case and result will hit recored at 100 level, 1000 level, 1w level and 10w level, and the test result as follows:

|                                                                |100/s  |1k/s   |1w/s    |10w/s   |
|----------------------------------------------------------------|-------|-------|--------|--------|
|                                                         oap 0.3| 95.851| 97.979| 111.846| 169.535|
|                                                  master version| 96.572| 95.621| 106.115| 163.954|
|                                                   with  this pr| 94.390| 96.382| 107.967| 167.869|

I think there are no significant performance differences between the three versions so far~

**Comment by LuciferYang** [comment]
@linhong-intel The 2nd case is creating `OAP index is skipped` scene which filter will fetch 90% of data set, the test result as follows:
|                                                                |1  |2   |3    |4   |5   |avg   |
|----------------------------------------------------------------|-------|-------|--------|--------|
|                                                         oap 0.3| 344.269| 339.611| 331.147| 335.272|337.959|337.652|
|                                                  master version| 321.536| 320.181| 323.118| 317.843|321.057|320.747|
|                                                   with  this pr| 316.933| 320.087| 317.086| 322.09|325.893|320.418|
|                                                   spark parquet| 323.769| 323.921| 312.113| 328.594|315.208|320.721|

There are no significant performance differences between master  version, with  this pr version, spark parquet version , and all above 3 versions are faster than oap-0.3 version because of `Vectorized Reader` optimization.

**Comment by LuciferYang** [comment]
Above 2 case base on 3.13 master snapshot version.

**Comment by linhong-intel** [comment]
close it first.

**Pull request closed without merging**
