### PR TITLE
Revert bitmap scanner

### PR DESCRIPTION
**Pull request by gczsjdy**
This reverts commit d5482085550e9d51c3699dafa95dd7372f69aa81.

## What changes were proposed in this pull request?

PR #629 may contain some potential issues, #781 is one example.
Revert it until we are confident with PR#629.

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by carsonwang** [comment]
How did you create this? Is it created by clicking the "revert" button on #629?

**Comment by gczsjdy** [comment]
It shows ` Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. `, I reverted it locally.

**Comment by linhong-intel** [comment]
lgtm
@lee-lei Please help review.
cc @LuciferYang

**Comment by carsonwang** [comment]
@gczsjdy , I've synced with @LuciferYang , let's revert it only in 0.4 branch.

**Comment by gczsjdy** [comment]
cc @LuciferYang

**Comment by LuciferYang** [comment]
LGTM

**Comment by linhong-intel** [comment]
cc @lee-lei

**Comment by lee-lei** [comment]
LGTM.

**Comment by carsonwang** [comment]
Merging.. Thanks all!

**Pull request merged**
