### PR TITLE
remove vector data cache related code

### PR DESCRIPTION
**Pull request by ivoson**
## What changes were proposed in this pull request?
remove parquet/orc vector data cache related code

## How was this patch tested?
existing ut.

### CODE REVIEW

**Comment by ivoson** [comment]
cc @LuciferYang @zhixingheyi-tian open this new pr for parquet/orc vector cache clean. Please have a review, thx.

**Comment by LuciferYang** [comment]
@ivoson `OnHeapColumnVector` in spark-2.4.x dir should  also be deleted.

**Comment by LuciferYang** [comment]
@ivoson line 189 of VectorizedColumnReader should revert 

`column.setDictionary(new ParquetDictionaryWrapper(dictionary));`

and `ParquetDictionaryWrapper` should also be deleted.

**Comment by LuciferYang** [comment]
@ivoson `ParquetDataFiberWriter` and related codes should also be deleted

**Comment by ivoson** [comment]
the last commit address the comments

**Comment by LuciferYang** [comment]
merge to master~

**Comment by jerrychenhf** [comment]
@LuciferYang  @ivoson @zhixingheyi-tian 
Since the binary cache is the new alternative for column vector, I would propose conservatively keep the column vector implementation for some time. Because 0.9 will have a quick BETA release by the end of June and I would guess at that time the binary cache may still not be widely verified. Let's still keep the column vector implementation in 0.9. We can make some cleanup this code so that it makes it easier for cache manager work to merge (because the cache manager work is based on the code removing column vector).

I have created a develop branch branch-remove-columnvector for keeping this work and on this branch, the cache manager work can be merged. 

We can then checkout how the cleanup be done on 0.9 (master) for column vector things so that the cache manager work can be merged easily from the dev branch to master. 

Does this make sense for folks? Sorry for this in conveniences.

**Comment by ivoson** [comment]
> @LuciferYang @ivoson @zhixingheyi-tian
> Since the binary cache is the new alternative for column vector, I would propose conservatively keep the column vector implementation for some time. Because 0.9 will have a quick BETA release by the end of June and I would guess at that time the binary cache may still not be widely verified. Let's still keep the column vector implementation in 0.9. We can make some cleanup this code so that it makes it easier for cache manager work to merge (because the cache manager work is based on the code removing column vector).
> 
> I have created a develop branch branch-remove-columnvector for keeping this work and on this branch, the cache manager work can be merged.
> 
> We can then checkout how the cleanup be done on 0.9 (master) for column vector things so that the cache manager work can be merged easily from the dev branch to master.
> 
> Does this make sense for folks? Sorry for causing these inconveniences.

copy that, it makes sense to me.

**Pull request merged**
