### PR TITLE
[OAP-1457][oap-native-sql] Reserve Spark off-heap execution memory after buffer allocation

### PR DESCRIPTION
**Pull request by zhztheplayer**
See #1457

### CODE REVIEW

**Comment by zhouyuan** [comment]
@zhztheplayer thanks for the efforts! could you please modify the travis tests? 
https://github.com/Intel-bigdata/OAP/blob/master/.travis.yml#L52-L55

`mvn clean package -pl oap-native-sql/core -DskipTests -am` should work I think

**Comment by zhztheplayer** [comment]
@zhouyuan Thanks Yuan.

Besides, is there a recommended way to test against the changes to oap-native-sql? So far I am not 100% confident with them.

**Comment by zhouyuan** [comment]
@zhztheplayer there's a local jenkins cluster to exercise oa-native-sql code with some queires from tpch/tpcds. there are several unit tests for native codes. let me try to enable this in travis.

**Comment by zhztheplayer** [comment]
@xuechendi @zhouyuan @rongma1997 @rui-mo 

The changes would make `oap-native-sql` to depend on module `arrow-datasource-common` at both compile time and runtime. Which may require developer to pre-install the latter in local maven repository or to run maven with option `-pl` if you haven't do this yet.

Please review or let me know if any problem with the PR.

**Pull request merged**
