### PR TITLE
Remove range tests from bitmap index suite

### PR DESCRIPTION
**Pull request by lee-lei**
## What changes were proposed in this pull request?
Remove the range query tests, since bitmap only supports equal query.
## How was this patch tested?
unit tests

### CODE REVIEW

**Comment by xuanyuanking** [comment]
The implementation of before version can support range filter, if this hard to implement in current code base, we can leave some comments in tests.
Currently in Baidu internal env we are implementing the statistics module to quantitate each user cases, so we may have detail data to support this feature need or not.
@adrian-wang What do you think？

**Comment by adrian-wang** [comment]
@xuanyuanking We discussed this in internal weekly meeting yesterday, the implementation is not an issue, but we want to make user to easily figure out what type of index they are looking for. If this is found important in real-world work loads, we can talk about it and bring it back. 
\cc @chenghao-intel

**Comment by lee-lei** [comment]
Actually the existing bitmap index implementation supports range filters. From my understanding, the plan is to make bitmap index only support equal query for column with not many unique keys. Therefore I am removing the redundant range query support. Thanks.

**Comment by xuanyuanking** [comment]
> If this is found important in real-world work loads, we can talk about it and bring it back.
Yep, that's what I'm thinking, after getting detail user statistics later and decide this, just leave some comments now.

**Comment by lee-lei** [comment]
Got it. Thanks for sharing your thoughts.

**Comment by chenghao-intel** [comment]
thank you @xuanyuanking , we can talk about the range index case in next offline meeting with you. :)

**Comment by lee-lei** [comment]
Close this PR now. If we need to remove the range tests in the future, then reopen it. Thanks.

**Pull request closed without merging**
