### PR TITLE
[OAP-1955][OAP-CACHE][POAE7-660]preferLocation low hit rate fix

### PR DESCRIPTION
**Pull request by offthewall123**
## What changes were proposed in this pull request?

preferlocation low hit rate 

## How was this patch tested?
E2E

### CODE REVIEW

**Comment by offthewall123** [comment]
@jikunshang @winningsix Please take a review, thanks.

**Comment by jikunshang** [comment]
LGTM.

**Comment by jikunshang** [comment]
#1955

**Comment by jikunshang** [comment]
@haojinIntel  This is fix for #1955, I have cherry-pick to branch-1.0. Please verify this in nightly build at your convenience, thanks!

**Pull request merged**
