### PR TITLE
Add Cluster Performance TestSuite -- oap-perf-suite to OAP  

### PR DESCRIPTION
**Pull request by HongW2019**
## What changes were proposed in this pull request?

( add oap-perf-suite codes to src/test/ , and modify pom.xml)

## How was this patch tested?

(Passed all the unit tests, integration tests, manual tests)

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
@HongW2019 

OAP is a code Repo. Please remove those xxx.jar ...


Thanks.

**Comment by HongW2019** [comment]
Have removed the jars from the repo, thanks a lot for your reminder.

**Comment by HongW2019** [comment]
Have removed the jars from the repo, thanks a lot for your reminder.

**Comment by HongW2019** [comment]
Have removed the jars from the repo, thanks a lot for your reminder.@zhixingheyi-tian

**Pull request closed without merging**
