### PR TITLE
fix bug for hasAvailableIndex judging conditions.

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?
1、OapFileFormat.hasAvailableIndex : forall -> exists,  n colums use to query, one column can use index is enough
2、Remove redundant collection conversion by intellij...
## How was this patch tested?
1、FilterSuite."filtering parquet", the third sql should use  index a. 
2、We need white box testing to verify that sql case use expected index

### CODE REVIEW

**Comment by LuciferYang** [comment]
@adrian-wang @linhong-intel @yueawang

**Comment by yueawang** [comment]
Hi, @LuciferYang  Thanks for fixing. I should have a new API to check the index exactly match case instead of changing this one.
Just wonder why you remove IsNotNull? I think this filter should hit index too, any concern??

**Comment by LuciferYang** [comment]
Hi, @yueawang ,from code perspective you are right, IsNotNull should hit index like filter is  "a != null", but from business perspective , only 'a != null' filter condition maybe trigger parquet full table scan and ParquetDataFile is slow than VectorizedParquetRecordReader In this scene, so should we give up hit index  in this scene?

**Comment by LuciferYang** [comment]
@yueawang in the feture, should we use VectorizedParquetRecordReader to do the full table scan of parquet file?

**Comment by yueawang** [comment]
Hi, @LuciferYang, Yes, I think we would eventually ignore the IsNotNull in many cases because of the full scan, but my suggestion is that we leave it to IndexScanner which does the index selection job, but let it pass here. Because there also have some cases can be accelerated. For example, "select * from t where a is not null" and let us assume most a in t is null (a really corner case).
In spark, in most cases, IsNotNull is an auto-generated partner expression of other filter expressions, therefore in the real world, the case that indexScanner chooses IsNotNull as the index entry is very rare, i.e. most likely index scanner chooses other filters.
So, IsNotNull as it is a filter, I think in this available index checking place, it should be yes, and later becomes unselectable according to different situations. What's your opinion?

**Comment by LuciferYang** [comment]
@yueawang  ok, revert checkAttribute method ~

**Comment by yueawang** [comment]
Thanks for fixing! LGTM.

**Comment by yueawang** [comment]
@LuciferYang For full table scan on parquet, I think VectorizedParquetRecordReader can be used, I just heard it makes running fast, however, I did not found some docs told the advantages (or maybe disadvantages?) of the case when filtering data on vectorized data. Maybe we can do a few perf tests in future. Any other concern? @adrian-wang @linhong-intel @lee-lei

**Comment by adrian-wang** [comment]
LGTM

**Pull request merged**
