### PR TITLE
bump version to 0.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by carsonwang**
## What changes were proposed in this pull request?
I've created a 0.3 branch and cut a RC1 release. Let's do the benchmark based on 0.3.0-rc1. 
Bump the version in master to 0.4.0-SNAPSHOT. 

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by linhong-intel** [comment]
@carsonwang Found another test failure in this PR test
```
- skipped rows and selected rows *** FAILED ***
  1 did not equal 33 (FilterSuite.scala:962)
```

**Comment by carsonwang** [comment]
Yes. Did someone trigger the test again after the 1st failure?

**Comment by linhong-intel** [comment]
I trigger a retest to see if the "simple cache test" can reproduce again

**Comment by carsonwang** [comment]
I also see many other error messages related to cache.
```
 remove a fiber is in use
22:54:47.615 ERROR org.apache.spark.sql.execution.datasources.oap.filecache.CacheGuardian: Fibers pending on removal use too much memory, current: 15728640, max: 7340032
22:54:47.660 ERROR org.apache.spark.sql.execution.datasources.oap.filecache.CacheGuardian: Fibers pending on removal use too much memory, current: 31457280, max: 7340032
- wait for other thread release the fiber
22:54:53.171 ERROR org.apache.spark.sql.execution.datasources.oap.filecache.CacheGuardian: Fibers pending on removal use too much memory, current: 15729664, max: 7340032
```

**Comment by chenghao-intel** [comment]
or we may change the log output level to `warning`?

**Comment by linhong-intel** [comment]
sure and done in #523

**Comment by carsonwang** [comment]
Merging this and will track the failed test in a new issue.

**Pull request merged**
