### PR TITLE
New fix travis

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
@zhouyuan  
     Is this method feasible?

Thanks

**Comment by zhixingheyi-tian** [comment]
@zhouyuan 

Can refer for adjusting travis:
https://github.com/zhixingheyi-tian/OAP-T-Travis/tree/travis-arrow-shuffle
https://github.com/zhixingheyi-tian/OAP-T-Travis/tree/community-spark

**Comment by winningsix** [comment]
@zhixingheyi-tian How does it work? You mean the travis file?

**Comment by zhixingheyi-tian** [comment]
@winningsix 
I mean I created two demos， for install arrow and spark in  travis, and they can work

**Pull request closed without merging**
