### PR TITLE
[OAP-MLIB] optimize the data conversion and fix bugs

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?
This PR aim to fix the issue in [1626](https://github.com/Intel-bigdata/OAP/issues/1626). And it contains two changes:

1. optimize the GC overhead during data conversion.
2. fix the warning message when compile

## How was this patch tested?

manual test

### CODE REVIEW

**Comment by JkSelf** [comment]
@xwu99

**Comment by xwu99** [comment]
@JkSelf You need to file an issue first, and refer the PR to it.

**Comment by JkSelf** [comment]
@xwu99 updated.

**Review by xwu99 — CHANGES_REQUESTED** [review]

**Comment by xwu99** [comment]
@JkSelf There are some bugs for this PR. could you test it the kmeans-pyspark example?
I think this line should use dataForConversion
>> val partRows = dataForConversion.mapPartitionsWithIndex

But after this, there is still error when running.  KMeansDALImpl.scala:58

20/08/25 22:35:23 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 11.0 (TID 15, sr549, executor 2): java.util.NoSuchElementException: key not found: 1
        at scala.collection.immutable.Map$Map1.apply(Map.scala:114)
        at org.apache.spark.ml.clustering.KMeansDALImpl.$anonfun$runWithRDDVector$3(KMeansDALImpl.scala:58)
        at org.apache.spark.ml.clustering.KMeansDALImpl.$anonfun$runWithRDDVector$3$adapted(KMeansDALImpl.scala:57)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2(RDD.scala:889)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndex$2$adapted(RDD.scala:889)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)

**Comment by xwu99** [comment]
The above issue was reported #1658 and fixed in #1659

**Pull request merged**
