### PR TITLE
[OAP-CACHE] Backport 0.7 to 0.8 on April 20th

### PR DESCRIPTION
**Pull request by winningsix**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by winningsix** [comment]
cc @yma11 @HongW2019

**Comment by winningsix** [comment]
@yma11 @HongW2019 Please check it.

**Comment by yma11** [comment]
LGTM.

**Comment by HongW2019** [comment]
LGTM +1

**Pull request merged**
