### PR TITLE
[POM] automatically enable Checkstyle plugin when compile

### PR DESCRIPTION
**Pull request by adrian-wang**
## What changes were proposed in this pull request?

automatically enable Checkstyle plugin when compile, and fail the build if any violations

## How was this patch tested?

mvn test

### CODE REVIEW

**Comment by gczsjdy** [comment]
Seems currently it will also fail for violations?

**Comment by adrian-wang** [comment]
@gczsjdy No it will pass, not even run it.

**Comment by gczsjdy** [comment]
Thanks @adrian-wang Turns out this checks Java style.

**Comment by LuciferYang** [comment]
Thx @adrian-wang ~ It's time to do this check~

**Comment by adrian-wang** [comment]
merging, thanks @LuciferYang  @gczsjdy !

**Pull request merged**
