### PR TITLE
Spark 2.4.1 support - import spark 2.4.1 source code

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

Only import Spark source code from spark 2.4.1 in this PR. And the following PRs will make change.

## How was this patch tested?
N/A

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
@JkSelf 
In branch-0.6-spark-2.4.1. You can removed the "spark2.3.2" dir.

**Comment by LuciferYang** [comment]
After research. parquet-related code parts, there are many changes in the developer api, I had shared a code branch-0.6-spark-2.4.1 to @JkSelf , then we can follow up the issue together.

**Comment by JkSelf** [comment]
@zhixingheyi-tian I will remove the "spark2.3.2" dir in the following PRs. 
@LuciferYang  Thanks for your contributions! 
The imported classes for spark have done, Please help me review and merge. @LuciferYang @zhixingheyi-tian @shaowenzh

**Comment by LuciferYang** [comment]
@JkSelf `FileFormatDataWriter. Scala` is a newly introduced file from spark , need create an issue to record

**Pull request merged**
