### PR TITLE
POAE7-307 Rename PMemID to meaningful name

### PR DESCRIPTION
**Pull request by winningsix**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by winningsix** [comment]
cc @yma11 @yeyuqiang

**Comment by yeyuqiang** [comment]
LGTM

**Comment by yma11** [comment]
LGTM+1

**Comment by winningsix** [comment]
Thanks folks for the review!

**Pull request merged**
