### PR TITLE
Move the common writeHead to IndexUtils

### PR DESCRIPTION
**Pull request by lee-lei**
## What changes were proposed in this pull request?

writeHead is used by all index writers, so move to IndexUtils.

## How was this patch tested?

mvn clean test package

### CODE REVIEW

**Comment by adrian-wang** [comment]
writeHead is also in Permuterm index...

**Comment by lee-lei** [comment]
@adrian-wang @linhong-intel @yueawang Please help review and merge this PR if it's ready. Thanks.

**Comment by adrian-wang** [comment]
better add tests for `IndexUtils.writeHead`

**Comment by lee-lei** [comment]
@adrian-wang @linhong-intel Please help review and merge this PR if it's ready. Thanks.

**Comment by adrian-wang** [comment]
merged, thanks!

**Pull request merged**
