### PR TITLE
remove vector data cache related code

### PR DESCRIPTION
**Pull request by ivoson**
## What changes were proposed in this pull request?
remove vector data cache related code

## How was this patch tested?
existing ut

### CODE REVIEW

**Comment by ivoson** [comment]
cc @zhixingheyi-tian @LuciferYang

**Comment by LuciferYang** [comment]
@ivoson too many code conflicts, need rebase

**Comment by ivoson** [comment]
too many file changes involved after the rebase, maybe need to open a new pr

**Comment by LuciferYang** [comment]
@ivoson ok, please close this pr and open a new pr ~ thx ~

**Pull request closed without merging**
