### PR TITLE
[OAP-1852][oap-native-sql]Register HashMap to arrow memory pool

### PR DESCRIPTION
**Pull request by xuechendi**

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Hi @xuechendi , did you ever see errors like "corrupted size vs. prev_size" during tests on the changes?

I managed to cherry-pick your changes onto 1852 PR https://github.com/Intel-bigdata/OAP/pull/1891 then saw such errors appearing to stderr.

**Comment by zhouyuan** [comment]
@xuechendi UT failed

**Comment by zhztheplayer** [comment]
Hi Yuan, at here CI is not possible to pass without having the base Arrow PR https://github.com/Intel-bigdata/arrow/pull/97 merged

**Comment by zhouyuan** [comment]
@zhztheplayer 
i see, let's hold on a bit after we fix the arrow used in 1.0 branch
https://github.com/Intel-bigdata/OAP/blob/branch-1.0-spark-3.x/.travis.yml#L56

**Comment by zhouyuan** [comment]
patches added in #1891

**Pull request closed without merging**
