### PR TITLE
Add ColumnarBatch for VectorizedRead

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?

Copy ColumnarBatch.java & ColumnarBatchSuite.scala from spark-2.1 for Vectorized Read  
#536 task 1

## How was this patch tested?
ColumnarBatchSuite.scala

### CODE REVIEW

**Comment by LuciferYang** [comment]
@adrian-wang I agree with you, but there are two problems:
1.We will use ColumnarBatch.filteredRows to record which row is filtered, but  filteredRows is a private filed :(
2.FileSourceScanExec.doProduceVectorized write columnarBatchClz with hard coding, it's more expensive to change it :(

**Comment by LuciferYang** [comment]
@adrian-wang I will pay attention to ColumnarBatch's change in spark.

**Comment by adrian-wang** [comment]
@LuciferYang  Thanks for the explanation, I'm fine to merge this!

**Comment by LuciferYang** [comment]
@adrian-wang Thx~

**Pull request merged**
