### PR TITLE
[oap-native-sql][Scala] adding round support

### PR DESCRIPTION
**Pull request by rui-mo**

### CODE REVIEW

**Comment by mmoriaaa** [comment]
success running on Jenkins.

**Comment by zhouyuan** [comment]
@rui-mo can you do a rebase on this?

**Comment by rui-mo** [comment]
@zhouyuan rebased now, and this patch has some issue on decimal precision, may causing incorrect result.  Do we need to merge it?

**Comment by zhouyuan** [comment]
@rui-mo I saw there's a TODO() we could fix this when decimal support is ready

**Pull request merged**
