### PR TITLE
Merge branch nativesql spark 3.0.0

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

Merge Native SQL Engine to master

## How was this patch tested?

manually tested

### CODE REVIEW

**Comment by zhouyuan** [comment]
@jikunshang @offthewall123 I think I've picked the changes in travis for oap-cache, could you please take a look if it's right? 
https://github.com/Intel-bigdata/OAP/blob/branch-nativesql-spark-3.0.0/.travis.yml

**Comment by offthewall123** [comment]
> @jikunshang @offthewall123 I think I've picked the changes in travis for oap-cache, could you please take a look if it's right?
> https://github.com/Intel-bigdata/OAP/blob/branch-nativesql-spark-3.0.0/.travis.yml

Yes,that's right.

**Comment by jikunshang** [comment]
> > @jikunshang @offthewall123 I think I've picked the changes in travis for oap-cache, could you please take a look if it's right?
> > https://github.com/Intel-bigdata/OAP/blob/branch-nativesql-spark-3.0.0/.travis.yml
> 
> Yes,that's right.

LGTM.

**Comment by zhixingheyi-tian** [comment]
@zhouyuan 

Please use arrow branch oap-master in .travis.yml

Thanks

**Comment by zhouyuan** [comment]
fixed in #1343

**Pull request merged**
