### PR TITLE
more documentation

### PR DESCRIPTION
**Pull request by zjf2012**
Signed-off-by: jiafu.zhang@intel.com <jiafu.zhang@intel.com>

## What changes were proposed in this pull request?
add more remote shuffle documentation

### CODE REVIEW

**Comment by carsonwang** [comment]
@zjf2012 , this is a general purpose shuffle manager that works for any Hadoop Filesystem. In our report, we only write the doc for DAOS. In this document, can you make it general for Hadoop Filesystem. then write something special for DAOS as well.

**Comment by zjf2012** [comment]
> @zjf2012 , this is a general purpose shuffle manager that works for any Hadoop Filesystem. In our report, we only write the doc for DAOS. In this document, can you make it general for Hadoop Filesystem. then write something special for DAOS as well.

ok, I'll work with @gczsjdy on that.

**Comment by gczsjdy** [comment]
@zjf2012 Thank you! I created #1167

**Comment by zjf2012** [comment]
> @zjf2012 Thank you! I created #1167

ok, let me close this.

**Pull request closed without merging**
