### PR TITLE
Refactor SharedOapContextBase Inheritance hierarchy

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?

Prepare for #988, original we create SparkSession use `new SparkSession(sc)` method, it can not inject `SparkSessionExtensions`, use `SparkSession.Builder` to create `SparkSession`, then we can config `spark.sql.extensions` to inject `SparkSessionExtensions`.
On the other hand, this pr can reslove #877 

## How was this patch tested?

Existing Tests.

### CODE REVIEW

**Comment by LuciferYang** [comment]
@LinhongLiu

**Comment by LuciferYang** [comment]
cc @Greg Lee

**Comment by LuciferYang** [comment]
@gczsjdy this pr can resolve #877 #878

**Comment by gczsjdy** [comment]
@LuciferYang Good for you! After using this extension solution, we don't need OapEnv actually?

**Pull request merged**
