### PR TITLE
[oap-cache-oap] Decouple DAGScheduler.scala

### PR DESCRIPTION
**Pull request by lidinghao**
Change-Id: Ie1b3542c0381f8e229c88ee82f1e7a2554d6c159

## What changes were proposed in this pull request?
In OAP, we change DAGScheduler.scala to make sure DAGScheduler.getPreferredLocsInternal will return the cache location as the prefered location. But we can also achieve the same functionality as long as we return the host address as the form like "executor_[hostname]_[executorid]" which will be recognized as a ExecutorCacheTaskLocation by Spark automatically. Search TaskLocation code for more details.

## How was this patch tested?
unit tests

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
@lidinghao 

Merge it?

**Comment by lidinghao** [comment]
> @lidinghao
> 
> Merge it?

I don't have the write access to OAP repository, could you merge it ?

**Comment by lidinghao** [comment]
cc @LuciferYang

**Comment by LuciferYang** [comment]
LGTM

**Pull request merged**
