### PR TITLE
Decouple SparkEnv.scala

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?

Add a ShutdownHook(OapRuntime#stop) to `ShutdownHookManager`, it's execution priority is higher than `SparkContext`, so `OapRuntime#stop()` will before than `SparkEnv#stop()`

## How was this patch tested?

exits test

### CODE REVIEW

**Comment by zhixingheyi-tian** [comment]
Good Job！

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 

Let merge this?

**Comment by LuciferYang** [comment]
@ivoson will do relevant tests first

**Comment by ivoson** [comment]
I have made some tests, it works fine when shutdownhook called. If we call SparkContext.stop before shutdown, spark env stop will be called first, but it seems fine we stop OapRuntime after spark env stop.

**Comment by LuciferYang** [comment]
@ivoson merge master done

**Pull request merged**
