### PR TITLE
Use Coarse-grained fetch mode when returnColumnarBatch is true

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?

- `IndexedVectorizedOapRecordReader` use Coarse-grained fetch mode when returnColumnarBatch is true, no longer do `markAllFiltered ` and  `markValid`  by columnarBatch level rowids

- No longer call `isFiltered ` in `DataSourceScanExec.doProduceVectorized`  method

- Remove `markAllFiltered `, `markValid` and `isFiltered ` api in ColumnarBatch which add in #592

- Remove `ColumnarBatch` and `ColumnarBatchSuite` which Introduce from spark source

## How was this patch tested?

- mvn test -Pspark-2.1 pass

- mvn test -Pspark-2.2 pass

- mvn test -Pspark-2.3 pass 

- Do a performance comparison test use 100 sql from production environment which can use index

   - Serial test: results is Coarse-grained fetch mode  use 788s and Fine-grained mode use 963s, 97% sql Coarse-grained fetch mode will be better, the other 3% takes the same time.

   - Parallel test(100 * 5 sql run with parallel degree 5):  Coarse-grained fetch mode use 8649s and Fine-grained mode use 9991s

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @carsonwang @linhong-intel @gczsjdy @zhixingheyi-tian

**Comment by linhong-intel** [comment]
lgtm. really nice to see this performance improvement.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 
Has the performance been tested?

**Comment by LuciferYang** [comment]
@zhixingheyi-tian yes, p performance has been done.

**Comment by LuciferYang** [comment]
thx ~ @linhong-intel

**Pull request merged**
