### PR TITLE
bypass data file based on filter and column statistics

### PR DESCRIPTION
**Pull request by adrian-wang**
## What changes were proposed in this pull request?

Bypass file reading by looking at column statistics and pushed down filter.

## How was this patch tested?

added a suite

### CODE REVIEW

**Comment by linhong-intel** [comment]
Just FYI.
You can use below code if it helps.
```
minMax = getStatsFromSchema(schema).foreach(_.setMinMaxFromBytes(min, max))
minMax(i).getMin()
```

**Comment by adrian-wang** [comment]
Thanks Linhong, I'll update this soon.

**Comment by adrian-wang** [comment]
@linhong-intel , by using the method you mentioned, StringType data will also be casted to `Binary`

**Comment by linhong-intel** [comment]
I see. then your current is better.

**Pull request merged**
