### PR TITLE
make intialize only available in OapFileFormat

### LINKED ISSUE #647: OAP-Spark  FileFormat
### OAP 0.3.0 - Spark 2.1.0 API change -   FileFormat (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.execution.datasources.FileFormat:_
**Before:**  
`def inferSchema(sparkSession: SparkSession, options: Map[String, String],files: Seq[FileStatus]): Option[StructType]`
**After:**     
`def inferSchema: Option[StructType] `
**Reason:** 
Easy storage for data schema, we need to load schema from disk directly

### PR DESCRIPTION
**Pull request by adrian-wang**
## What changes were proposed in this pull request?

Fixes #647 

`initalize()` can be placed only in `OapFileFormat`, so that we don't need FileFormat.scala and other dependent source files in our repo to override upstream.

## How was this patch tested?

existed ut.

### CODE REVIEW

**Comment by adrian-wang** [comment]
For reviewers: if you want to run unit test locally, you need to explicitly run `mvn clean` to get rid of classes corresponding to deleted source files.

**Comment by gczsjdy** [comment]
We can change this now because `inferSchema` can be called with parameters?

**Comment by yueawang** [comment]
I think this is a good idea. Later if we want to support more formats, i.e. add index to them, we can add OapFileFormat wrapper just like so far we have done for parquet, rather than copy/hack so many fileformats from Spark upstream.
Just to confirm. Does parquet's OapFormat wrapper utilize this inferscheme?

**Comment by adrian-wang** [comment]
@yueawang when creating index on parquet, we are using ReadOnlyParquetFileFormat, just for reading data. When querying parquet, we are just using OapFileFormat.

**Comment by LuciferYang** [comment]
Good Job!!!!! @adrian-wang

**Pull request merged**
