### PR TITLE
[OAP-1568][OAP-cache] Cleanup Oap data format read/write related test cases

### PR DESCRIPTION
**Pull request by LuciferYang**
## What changes were proposed in this pull request?

This is a sub-task of #1337 to Replace all Oap data format read / write related cases with Parquet or ORC refer to #1505, then to ensure that subsequent changes will not be blocked

## How was this patch tested?

Existing UT passed

### CODE REVIEW

**Comment by LuciferYang** [comment]
cc @happycherry , and I create a new issue #1624, we need reorganize oap-cache module test cases

**Review by jerrychenhf — COMMENTED** [review]
The patch on change/remove all the unit test cases related on OAP format looks good to me.
Thank you @LuciferYang !

**Comment by jerrychenhf** [comment]
@LuciferYang As there are a lot changes and we ca go merge this one and move quickly on others.

**Comment by LuciferYang** [comment]
@jerrychenhf ok~ merge this to master first

**Pull request merged**
