### PR TITLE
[OAP-1941][oap-data-source][arrow] Implement splitable file scan

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Dependent PR: Intel-bigdata/arrow#99

**Comment by zhztheplayer** [comment]
@zhouyuan As discussed, the PRs are ready now

**Comment by zhouyuan** [comment]
@zhztheplayer verified locally with big parquet files. there's a bit overhead when split happen, but we could bypass this by setting `spark.sql.files.maxPartitionBytes 1G`

**Review by zhouyuan — APPROVED** [review]

**Comment by zhztheplayer** [comment]
Noted. Thanks!

**Pull request merged**
