### PR TITLE
remove parquet vector data cache related code

### PR DESCRIPTION
**Pull request by ivoson**
## What changes were proposed in this pull request?
remove parquet vector data cache related code

## How was this patch tested?
existing uts.

### CODE REVIEW

**Comment by ivoson** [comment]
cc @LuciferYang @zhixingheyi-tian

this pr do code clean for parquet vector data cache, while there are some files also used by orc vector cache, for that part, maybe we can do that when handle orc binary cache.

**Comment by LuciferYang** [comment]
cc @zhixingheyi-tian 
Should we merge Orc binary cache first and then clean up all vector cache include parquet & orc?

**Comment by zhixingheyi-tian** [comment]
@ivoson @LuciferYang 

After #1143 merged, I will propose ORC PRs, and merge ORC first.

Thanks.

**Comment by LuciferYang** [comment]
@zhixingheyi-tian I suggest that we merge ORC PRs first, then consider how to refactor  `BinaryFiberId` and I think The implementation of #1143 is not satisfactory.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 
It's also fine.

**Comment by LuciferYang** [comment]
@zhixingheyi-tian ok ~

**Comment by zhixingheyi-tian** [comment]
@ivoson 

Now  you can clean up  all vector cache.

Thanks

**Comment by ivoson** [comment]
> @ivoson
> 
> Now you can clean up all vector cache.
> 
> Thanks

@zhixingheyi-tian I have open a new pr https://github.com/Intel-bigdata/OAP/pull/1149 for this.  Please give a review. 

And closing this pr.

**Pull request closed without merging**
